"""add update_user_notification_preferences

Revision ID: 67899ad92947
Revises: e5d108a97723
Create Date: 2026-06-03 08:50:25.002422

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "67899ad92947"
down_revision: str | None = "e5d108a97723"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
