from app.core.exceptions.base import (
    AccountLockedError,
    BadgeAlreadyPublishedError,
    BadgeNotFoundError,
    BadgeRenderError,
    CloudinaryUploadError,
    EmailAlreadyVerifiedError,
    EmailConflictError,
    EmailDeliveryError,
    EmailNotVerifiedError,
    GoogleOAuthError,
    InvalidCredentialsError,
    InvalidPasswordResetTokenError,
    InvalidRefreshTokenError,
    NotBadgeOwnerError,
    PlatformTemplateNotFoundError,
    PublicBadgeNotFoundError,
)
from app.core.exceptions.handlers import register_exception_handlers

__all__ = [
    "register_exception_handlers",
    "BadgeRenderError",
    "EmailAlreadyVerifiedError",
    "EmailConflictError",
    "EmailDeliveryError",
    "EmailNotVerifiedError",
    "GoogleOAuthError",
    "BadgeNotFoundError",
    "InvalidCredentialsError",
    "InvalidPasswordResetTokenError",
    "InvalidRefreshTokenError",
    "BadgeAlreadyPublishedError",
    "AccountLockedError",
    "NotBadgeOwnerError",
    "PlatformTemplateNotFoundError",
    "PublicBadgeNotFoundError",
    "CloudinaryUploadError",
]
